import React, { useRef, useState } from "react";
import { Camera, Loader2 } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { API_BASE_URL } from "@/config/api";

type AvatarUploadProps = {
  currentAvatarUrl: string;
  onUploadSuccess: (url: string) => void;
  onUploadError: (error: string) => void;
};

const ALLOWED_AVATAR_TYPES = new Set([
  "image/jpeg",
  "image/png",
  "image/gif",
  "image/webp",
]);

export const AvatarUpload: React.FC<AvatarUploadProps> = ({
  currentAvatarUrl,
  onUploadSuccess,
  onUploadError,
}) => {
  const [isUploading, setIsUploading] = useState(false);
  const fileInputRef = useRef<HTMLInputElement>(null);

  const handleFileChange = async (
    event: React.ChangeEvent<HTMLInputElement>
  ) => {
    const file = event.target.files?.[0];
    if (!file) return;

    if (!ALLOWED_AVATAR_TYPES.has(file.type)) {
      onUploadError(
        "Please select a valid image file (JPG, PNG, GIF, or WebP)."
      );
      return;
    }

    // Client-side pre-check for 50MB (though backend enforces it as well)
    if (file.size > 50 * 1024 * 1024) {
      onUploadError(
        "Image is too large. Please upload an image smaller than 50MB."
      );
      return;
    }

    setIsUploading(true);

    try {
      const session = await supabase.auth.getSession();
      const token = session.data.session?.access_token;

      const user = session.data.session?.user;

      if (!user) {
        throw new Error(
          "You must be signed in before uploading a profile picture."
        );
      }

      // The storage path is generated by the backend from the authenticated
      // user's id — the client no longer sends a filePath. "folder" must be
      // appended before "file" so the backend can read it before it starts
      // streaming the file (see uploadController.js fileFilter).
      const formData = new FormData();
      formData.append("folder", "avatars");
      formData.append("file", file);

      const res = await fetch(`${API_BASE_URL}/api/upload`, {
        method: "POST",
        headers: {
          Authorization: `Bearer ${token}`,
        },
        body: formData,
      });

      if (!res.ok) {
        if (res.status === 401) {
          throw new Error(
            "Your session has expired. Please sign in again and retry the upload."
          );
        }

        if (res.status === 413) {
          throw new Error(
            "Image is too large. Please upload an image smaller than 50MB."
          );
        }

        throw new Error(
          `Unable to upload your profile picture. Please try again. (${res.status})`
        );
      }

      const uploadResponse = await res.json();

      if (uploadResponse.success && uploadResponse.data?.url) {
        onUploadSuccess(uploadResponse.data.url);
      } else {
        throw new Error(
          "The server returned an unexpected response. Please try again."
        );
      }
    } catch (err: any) {
      onUploadError(
        err.message ||
          "Unable to upload your profile picture. Please try again later."
      );
    } finally {
      setIsUploading(false);

      if (fileInputRef.current) {
        fileInputRef.current.value = "";
      }
    }
  };

  return (
    <div className="relative inline-block">
      <img
        src={currentAvatarUrl}
        alt="User profile avatar"
        className={`w-36 h-36 rounded-full border-4 border-cyan-400 object-cover shadow-2xl shadow-cyan-500/20 ${
          isUploading ? "opacity-70" : ""
        }`}
      />

      <input
        type="file"
        ref={fileInputRef}
        accept="image/jpeg,image/png,image/gif,image/webp"
        onChange={handleFileChange}
        className="hidden"
      />

      <button
        type="button"
        onClick={() => {
          if (!isUploading) {
            fileInputRef.current?.click();
          }
        }}
        disabled={isUploading}
        aria-label={isUploading ? "Uploading avatar" : "Upload avatar"}
        aria-busy={isUploading}
        className="absolute bottom-2 right-2 bg-cyan-400 p-3 rounded-full hover:bg-cyan-300 transition-colors disabled:opacity-50"
      >
        {isUploading ? (
          <Loader2 size={20} className="text-black animate-spin" />
        ) : (
          <Camera size={20} className="text-black" />
        )}
      </button>
      {isUploading && (
        <p
          role="status"
          aria-live="polite"
          className="absolute -bottom-8 left-1/2 -translate-x-1/2 whitespace-nowrap text-xs text-cyan-400"
        >
          Uploading avatar...
        </p>
      )}
    </div>
  );
};
